/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/welcome" |
       "/pages/button-demo" |
       "/pages/iconfont-demo" |
       "/pages/websocket-demo" |
       "/pages/index/add" |
       "/pages/index/community" |
       "/pages/index/goods" |
       "/pages/index/message" |
       "/pages/index/personal";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/community" | "/pages/index/goods" | "/pages/index/add" | "/pages/index/message" | "/pages/index/personal"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
