/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/welcome" |
       "/pages/action-sheet-demo" |
       "/pages/button-demo" |
       "/pages/iconfont-demo" |
       "/pages/websocket-demo" |
       "/pages/index/add" |
       "/pages/index/community" |
       "/pages/index/goods" |
       "/pages/index/message" |
       "/pages/index/personal" |
       "/subpackages/pages/message/private_chat" |
       "/subpackages/pages/message/notification_chat" |
       "/subpackages/pages/message/private_chat_more" |
       "/subpackages/pages/register/step1" |
       "/subpackages/pages/register/step2" |
       "/subpackages/pages/register/step3" |
       "/subpackages/pages/register/finish" |
       "/subpackages/pages/community/post-detail" |
       "/subpackages/pages/community/community-search" |
       "/subpackages/pages/community/publish-post" |
       "/subpackages/pages/community/report" |
       "/subpackages/pages/community/community-personal-center" |
       "/subpackages/pages/goods/categories" |
       "/subpackages/pages/goods/goods-details" |
       "/subpackages/pages/goods/order-confirm" |
       "/subpackages/pages/goods/addresses" |
       "/subpackages/pages/goods/pay-confirm" |
       "/subpackages/pages/goods/goods-publish-category" |
       "/subpackages/pages/goods/goods-publish-submit" |
       "/subpackages/pages/goods/goods-personal-center" |
       "/subpackages/pages/profile/choose-avatar";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/community" | "/pages/index/goods" | "/pages/index/add" | "/pages/index/message" | "/pages/index/personal"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
