/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppLogos: typeof import('./../components/AppLogos.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    CustomStatusBar: typeof import('./../components/customStatusBar.vue')['default']
    CustomTabBar: typeof import('./../components/customTabBar.vue')['default']
    IconFont: typeof import('./../components/IconFont.vue')['default']
    InputEntry: typeof import('./../components/InputEntry.vue')['default']
    TabGroup: typeof import('./../components/TabGroup.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
  }
}
